---
- name: Install NVIDIA Docker 2
  hosts: all
  become: true
  tasks:
    - include_tasks: install_docker.yml
    - name: Install required system packages for NVIDIA Docker
      ansible.builtin.apt:
        name:
          - nvidia-driver-440
        state: latest
        update_cache: true
    - name: Add NVIDIA signing key
      ansible.builtin.apt_key:
        url: "https://nvidia.github.io/libnvidia-container/gpgkey"
        state: present
        keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    - name: Add NVIDIA repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/$(ARCH) /"
        state: present
        filename: nvidia-container-toolkit
    - name: Install NVIDIA Docker 2
      ansible.builtin.apt:
        name:
          - nvidia-docker2
        state: latest
        update_cache: true
    - name: Restart Docker
      ansible.builtin.systemd:
        state: restarted
        name: docker