services:
  gance-develop:
    container_name: gance-develop
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2222:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0,', '1', '2', '3']
              capabilities: [gpu]
    environment:
      - DISPLAY=:0
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - type: bind
        source: /home/devon/development_share/yac_assets
        target: /home/gpu/gance/gance/assets/
        read_only: true
      - type: bind
        source: /home/devon/development_share/yac_output
        target: /home/gpu/gance/gance/assets/output
        read_only: false
      - type: bind
        source: ./test/assets
        target: /home/gpu/gance/test/assets
        read_only: true
