services:
  gance-develop:
    container_name: gance-develop
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2222:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./gance/assets/
        target: /home/gpu/gance/gance/assets/
        read_only: true
      - type: bind
        source: /home/devon/development_share/yac_output
        target: /home/gpu/gance/gance/assets/output
        read_only: false
      - type: bind
        source: ./test/assets
        target: /home/gpu/gance/test/assets
        read_only: true
  gance-develop-1:
    container_name: gance-develop-1
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2223:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '2']
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./gance/assets/
        target: /home/gpu/gance/gance/assets/
        read_only: true
      - type: bind
        source: /home/devon/development_share/yac_output
        target: /home/gpu/gance/gance/assets/output
        read_only: false
      - type: bind
        source: ./test/assets
        target: /home/gpu/gance/test/assets
        read_only: true

