services:
  develop:
    container_name: develop
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2222:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes: # TODO: This should be abstracted before publication
      - type: bind
        source: ./yellow_album_cover/assets/models
        target: /home/gpu/yellow_album_cover/yellow_album_cover/assets/models
        read_only: true
      - type: bind
        source: /home/devon/development_share/yac_output
        target: /home/gpu/yellow_album_cover/yellow_album_cover/assets/output
        read_only: false
      - type: bind
        source: /home/devon/development_share/records/luke_batch_2
        target: /home/gpu/yellow_album_cover/yellow_album_cover/assets/datasets/luke_batch_2
        read_only: true
      - type: bind
        source: /home/devon/development_share/good_batch_2_models
        target: /home/gpu/yellow_album_cover/finals_input
        read_only: true
      - type: bind
        source: /home/devon/development_share/final_batch_2_models
        target: /home/gpu/yellow_album_cover/finals_output
        read_only: false
      - type: bind
        source: /home/devon/development_share/prod_covers
        target: /home/gpu/yellow_album_cover/prod_covers
        read_only: false
      - type: bind
        source: /home/devon/development_share/projection_file_output
        target: /home/gpu/yellow_album_cover/projection_file_output
        read_only: false

  projector_1:
    container_name: projector_1
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2201:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes: # TODO: This should be abstracted before publication
      - type: bind
        source: ./yellow_album_cover/assets/models/final_batch_2_model.pkl
        target: /home/gpu/yellow_album_cover/final_batch_2_model.pkl
        read_only: true
      - type: bind
        source: /home/devon/development_share/projection_file_output
        target: /home/gpu/yellow_album_cover/projection_file_output
        read_only: false
      - type: bind
        source: ./yellow_album_cover/assets/prod_projection_videos/projector_1
        target: /home/gpu/yellow_album_cover/video_inputs
        read_only: false

  projector_2:
    container_name: projector_2
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2202:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    volumes: # TODO: This should be abstracted before publication
      - type: bind
        source: ./yellow_album_cover/assets/models/final_batch_2_model.pkl
        target: /home/gpu/yellow_album_cover/final_batch_2_model.pkl
        read_only: true
      - type: bind
        source: /home/devon/development_share/projection_file_output
        target: /home/gpu/yellow_album_cover/projection_file_output
        read_only: false
      - type: bind
        source: ./yellow_album_cover/assets/prod_projection_videos/projector_2
        target: /home/gpu/yellow_album_cover/video_inputs
        read_only: false

  projector_3:
    container_name: projector_3
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "2203:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    volumes: # TODO: This should be abstracted before publication
      - type: bind
        source: ./yellow_album_cover/assets/models/final_batch_2_model.pkl
        target: /home/gpu/yellow_album_cover/final_batch_2_model.pkl
        read_only: true
      - type: bind
        source: /home/devon/development_share/projection_file_output
        target: /home/gpu/yellow_album_cover/projection_file_output
        read_only: false
      - type: bind
        source: ./yellow_album_cover/assets/prod_projection_videos/projector_3
        target: /home/gpu/yellow_album_cover/video_inputs
        read_only: false

  create_dataset:
    container_name: create_dataset
    build:
      context: .
      dockerfile: create_dataset.Dockerfile
    volumes:
      - type: bind
        source: /home/devon/Documents/yellow_album_cover/faces/datasets/luke
        target: /home/root/faces/datasets
      - type: bind
        source: /home/devon/development_share/scaled
        target: /home/root/faces/images

  train:
    container_name: train
    build:
      context: .
      dockerfile: train.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - type: bind
        source: /home/devon/Documents/yellow_album_cover/faces/results
        target: /home/root/faces/results/
      - type: bind
        source: /home/devon/Documents/yellow_album_cover/faces/datasets
        target: /home/root/faces/datasets/
