services:
  gance-develop:
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - "22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./gance/assets/
        target: /home/gpu/gance/gance/assets/
        read_only: true
      - type: bind
        source: /home/devon/development_share/yac_output
        target: /home/gpu/gance/gance/assets/output
        read_only: false
      - type: bind
        source: ./test/assets
        target: /home/gpu/gance/test/assets
        read_only: true

